# Generated by Django 3.2.6 on 2021-09-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descript',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
